legend = ["LAT_ACCEL_FACTOR", "MAX_LAT_ACCEL_MEASURED", "FRICTION"]
"ACURA ILX 2016" = [1.524988973896102, 0.519011053086259, 0.34236219253028]
"ACURA RDX 2018" = [0.9987728568686902, 0.5323765166196301, 0.303218805715844]
"ACURA RDX 2020" = [1.4314459806646749, 0.33874701282109954, 0.18048847083897598]
"AUDI A3 3RD GEN" = [1.5122414863077502, 1.7443517531719404, 0.15194151892450905]
"AUDI Q3 2ND GEN" = [1.4439223359448605, 1.2254955789112076, 0.1413798895978097]
"CHEVROLET VOLT PREMIER 2017" = [1.5961527626411784, 1.8422651988094612, 0.1572393918005158]
"CHRYSLER PACIFICA 2018" = [2.07140, 1.3366521181047952, 0.13776367250652022]
"CHRYSLER PACIFICA 2020" = [1.86206, 1.509076559398423, 0.14328246159386085]
"CHRYSLER PACIFICA HYBRID 2017" = [1.79422, 1.06831764583744, 0.116237]
"CHRYSLER PACIFICA HYBRID 2018" = [2.08887, 1.2943025830995154, 0.114818]
"CHRYSLER PACIFICA HYBRID 2019" = [1.90120, 1.1958788168371808, 0.131520]
"HONDA ACCORD 2018" = [1.7135052593468778, 0.3461280068322071, 0.21579936052863807]
"HONDA ACCORD HYBRID 2018" = [1.6651615004829625, 0.30322180951193245, 0.2083000440586149]
"HONDA CIVIC (BOSCH) 2019" = [1.691708637466905, 0.40132900729454185, 0.25460295304024094]
"HONDA CIVIC 2016" = [1.6528895627785531, 0.4018518740819229, 0.25458812851328544]
"HONDA CR-V 2016" = [0.7667141440182675, 0.5927571534745969, 0.40909087636157127]
"HONDA CR-V 2017" = [2.01323205142022, 0.2700612209345081, 0.2238412881331528]
"HONDA CR-V HYBRID 2019" = [2.072034634644233, 0.7152085160516978, 0.20237105008376083]
"HONDA FIT 2018" = [1.5719981427109775, 0.5712761407108976, 0.110773383324281]
"HONDA HRV 2019" = [2.0661212805710205, 0.7521343418694775, 0.17760375789242094]
"HONDA INSIGHT 2019" = [1.5201671214069354, 0.5660229120683284, 0.25808042580281876]
"HONDA ODYSSEY 2018" = [1.8774809275211801, 0.8394431662987996, 0.2096978613792822]
"HONDA PILOT 2017" = [1.7262026201812795, 0.9470005614967523, 0.21351430733218763]
"HONDA RIDGELINE 2017" = [1.4146525028237624, 0.7356572861629564, 0.23307177552211328]
"JEEP GRAND CHEROKEE 2019" = [2.30972, 1.289689569171081, 0.117048]
"JEEP GRAND CHEROKEE V6 2018" = [2.27116, 1.4057367824262523, 0.11725947414922003]

"HYUNDAI AVANTE,I30 (AD,PD)" = [2.2200457811703953, 1.2967330275895228, 0.14039920986586393]
"HYUNDAI AVANTE (CN7)" = [3.284505627881726, 2.1259108157250735, 0.08452048323586728]
"HYUNDAI AVANTE HEV (CN7)" = [3.284505627881726, 2.1259108157250735, 0.08452048323586728]
"HYUNDAI SONATA (DN8)" = [2.9638737459977467, 2.1259108157250735, 0.07813665616927593]
"HYUNDAI SONATA HEV (DN8)" = [2.8990264092395734, 2.061410192222139, 0.0899805488717382]
"HYUNDAI SONATA (LF)" = [2.2200457811703953, 1.2967330275895228, 0.14039920986586393]
"HYUNDAI SONATA HEV (LF)" = [2.2200457811703953, 1.2967330275895228, 0.14039920986586393]
"HYUNDAI KONA (OS)" = [4.398306735170212, 3.2961956260770484, 0.08651833437845884]
"HYUNDAI KONA EV (OS)" = [4.398306735170212, 3.2961956260770484, 0.08651833437845884]
"HYUNDAI KONA HEV (OS)" = [4.398306735170212, 3.2961956260770484, 0.08651833437845884]
"HYUNDAI IONIQ (AE)" = [1.7662975472852054, 1.613755614526594, 0.17087579756306276]
"HYUNDAI IONIQ EV (AE)" = [1.7662975472852054, 1.613755614526594, 0.17087579756306276]
"HYUNDAI IONIQ HEV (AE)" = [3.2928700076638537, 2.1193482926455656, 0.12463700961468778]
"HYUNDAI TUCSON (TL)" = [3.0787027729757632, 2.6173437483495565, 0.1207019341823945]
"HYUNDAI SANTAFE (TM)" = [3.0787027729757632, 2.6173437483495565, 0.1207019341823945]
"HYUNDAI SANTAFE HEV (TM)" = [3.501877602644835, 2.729064118456137, 0.10384068104538963]
"HYUNDAI PALISADE (LX2)" = [2.544642494803999, 1.8721703683337008, 0.1301424599248651]
"HYUNDAI VELOSTER (JS)" = [2.2200457811703953, 1.2967330275895228, 0.14039920986586393]
"HYUNDAI GRANDEUR (IG)" = [3.284505627881726, 2.1259108157250735, 0.08452048323586728]
"HYUNDAI GRANDEUR HEV (IG)" = [3.284505627881726, 2.1259108157250735, 0.08452048323586728]
"HYUNDAI GRANDEUR (IG_FL)" = [3.284505627881726, 2.1259108157250735, 0.08452048323586728]
"HYUNDAI GRANDEUR HEV (IG_FL)" = [3.284505627881726, 2.1259108157250735, 0.08452048323586728]
"HYUNDAI NEXO (FE)" = [3.284505627881726, 2.1259108157250735, 0.08452048323586728]

"KIA K3 (BD)" = [2.2200457811703953, 1.2967330275895228, 0.14039920986586393]
"KIA K5 (JF)" = [2.9638737459977467, 2.1259108157250735, 0.07813665616927593]
"KIA K5 HEV (JF)" = [2.9638737459977467, 2.1259108157250735, 0.07813665616927593]
"KIA K5 (DL3)" = [2.405339728085138, 1.460032270828705, 0.11650989850813716]
"KIA K5 HEV (DL3)" = [2.405339728085138, 1.460032270828705, 0.11650989850813716]
"KIA K7 (YG)" = [2.405339728085138, 1.460032270828705, 0.11650989850813716]
"KIA K7 HEV (YG)" = [2.405339728085138, 1.460032270828705, 0.11650989850813716]
"KIA K9 (RJ)" = [2.405339728085138, 1.460032270828705, 0.11650989850813716]
"KIA SPORTAGE (QL)" = [2.464854685101844, 1.5335274218367956, 0.12056170567599558]
"KIA SORENTO (UM)" = [2.464854685101844, 1.5335274218367956, 0.12056170567599558]
"KIA MOHAVE (HM)" = [2.464854685101844, 1.5335274218367956, 0.12056170567599558]
"KIA STINGER (CK)" = [2.7499043387418967, 1.849652021986449, 0.12048334239559202]
"KIA NIRO EV (DE)" = [2.9215954981365337, 2.1500583840260044, 0.09236802474810267]
"KIA NIRO HEV (DE)" = [2.9215954981365337, 2.1500583840260044, 0.09236802474810267]
"KIA SOUL EV (SK3)" = [2.9215954981365337, 2.1500583840260044, 0.09236802474810267]
"KIA SELTOS (SP2)" = [3.284505627881726, 2.1259108157250735, 0.08452048323586728]

"GENESIS (DH)" = [2.7807965280270794, 2.325, 0.0984484465421171]
"GENESIS G70 (IK)" = [3.8520195946707947, 2.354697063349854, 0.06830285485626221]
"GENESIS G80 (DH)" = [3.8520195946707947, 2.354697063349854, 0.06830285485626221]
"GENESIS G90 (HI)" = [3.8520195946707947, 2.354697063349854, 0.06830285485626221]

# CANFD
"HYUNDAI IONIQ 5 (NE1)" = [3.172929, 2.713050, 0.096019]
"HYUNDAI IONIQ 6 (CE1)" = [2.5, 2.5, 0.1]
"HYUNDAI TUCSON (NX4)" = [3.2, 3.0, 0.05]
"HYUNDAI TUCSON HEV (NX4)" = [3.2, 3.0, 0.05]
"HYUNDAI KONA EV (SX2)" = [2.5, 2.5, 0.1]
"HYUNDAI STARIA (US4)" = [2.0, 2.0, 0.12]
"HYUNDAI SONATA_2024 (DN8)" = [2.5, 2.5, 0.1]

"KIA EV6 (CV)" = [3.2, 2.093457, 0.05]
"KIA SPORTAGE (NQ5)" = [2.7, 2.7, 0.1]
"KIA SPORTAGE HEV (NQ5)" = [2.5, 2.5, 0.1]
"KIA SORENTO (MQ4)" = [2.5, 2.5, 0.1]
"KIA SORENTO HEV (MQ4)" = [2.5, 2.5, 0.1]
"KIA NIRO EV (SG2)" = [2.5, 2.5, 0.1]
"KIA NIRO HEV (SG2)" = [2.5, 2.5, 0.1]
"KIA CARNIVAL (KA4)" = [1.75, 1.75, 0.15]
"KIA K8 (GL3)" = [2.5, 2.5, 0.1]
"KIA K8 HEV (GL3)" = [2.5, 2.5, 0.1]
"KIA EV9 (MV)" = [1.75, 1.75, 0.15]
"GENESIS GV60 (JW1)" = [2.5, 2.5, 0.1]
"GENESIS GV70 (JK1)" = [2.42, 2.42, 0.1]
"GENESIS GV80 (JX1)" = [2.5, 2.5, 0.1]
"KIA K5_2024 (DL3)" = [2.5, 2.5, 0.1]
"KIA K5_2024 HEV (DL3)" = [2.5, 2.5, 0.1]

"LEXUS ES 2019" = [2.0357564999999997, 1.999082295195227, 0.101533]
"LEXUS NX 2018" = [2.3525924753753613, 1.9731412277641067, 0.15168101064205927]
"LEXUS NX 2020" = [2.4331999786982936, 2.1045680431705414, 0.14099899317761067]
"LEXUS RX 2016" = [1.5876816543130423, 1.0427699298523752, 0.21334066732397142]
"LEXUS RX 2020" = [1.5375561442049257, 1.343166476215164, 0.1931062001527557]
"LEXUS RX HYBRID 2017" = [1.6984261557042386, 1.3211501880159107, 0.1820354534928893]
"MAZDA CX-9 2021" = [1.7601682915983443, 1.0889677335154337, 0.17713792194297195]
"SKODA SUPERB 3RD GEN" = [1.166437404652981, 1.1686163012668165, 0.12194533036948708]
"SUBARU FORESTER 2019" = [3.6617001649776793, 2.342197172531713, 0.11075960785398745]
"SUBARU IMPREZA LIMITED 2019" = [1.0670704910352047, 0.8234374840709592, 0.20986563268614938]
"SUBARU IMPREZA SPORT 2020" = [2.6068223389108303, 2.134872342760203, 0.15261513193561627]
"TOYOTA AVALON 2016" = [2.5185770183845646, 1.7153346784214922, 0.10603968787111022]
"TOYOTA AVALON 2019" = [1.7036141952825095, 1.239619084240008, 0.08459830394899492]
"TOYOTA AVALON 2022" = [2.3154403649717357, 2.7777922854327124, 0.11453999639164605]
"TOYOTA C-HR 2018" = [1.5591084333664578, 1.271271459066948, 0.20259087058453193]
"TOYOTA C-HR 2021" = [1.7678810166088303, 1.3742176337919942, 0.2319674583741509]
"TOYOTA CAMRY 2018" = [2.0568162685952505, 1.7576185169559122, 0.108878753]
"TOYOTA CAMRY 2021" = [2.3548324999999997, 2.368900128946771, 0.118436]
"TOYOTA COROLLA 2017" = [3.117154369115421, 1.8438132575043773, 0.12289685869250652]
"TOYOTA COROLLA TSS2 2019" = [1.991132339206426, 1.868866242720403, 0.19570063298031432]
"TOYOTA HIGHLANDER 2017" = [1.8696367437248915, 1.626293990451463, 0.17485372210240796]
"TOYOTA HIGHLANDER 2020" = [1.9617570834136164, 1.8611643317268927, 0.14519673256119725]
"TOYOTA HIGHLANDER HYBRID 2018" = [1.752033, 1.6433903296845025, 0.144600]
"TOYOTA MIRAI 2021" = [2.506899832157829, 1.7417213930750164, 0.20182618449440565]
"TOYOTA PRIUS 2017" = [1.60, 1.5023147650693636, 0.151515]
"TOYOTA PRIUS TSS2 2021" = [1.972600, 1.9104337425537743, 0.170968]
"TOYOTA RAV4 2017" = [2.085695074355425, 2.2142832316984733, 0.13339165270103975]
"TOYOTA RAV4 2019" = [2.279239424615458, 2.087101966779332, 0.13682208413446817]
"TOYOTA RAV4 2019 8965" = [2.3080951748210854, 2.1189367835820603, 0.12942102328134028]
"TOYOTA RAV4 2019 x02" = [2.762293266024922, 2.243615865975329, 0.11113568178327986]
"TOYOTA RAV4 HYBRID 2017" = [1.9796257271652042, 1.7503987331707576, 0.14628860048885406]
"TOYOTA RAV4 2022" = [2.241883248393209, 1.9304407208090029, 0.112174]
"TOYOTA RAV4 2022 x02" = [3.044930631831037, 2.3979189796380918, 0.14023209146703736]
"TOYOTA SIENNA 2018" = [1.689726, 1.3208264576110418, 0.140456]
"VOLKSWAGEN ARTEON 1ST GEN" = [1.45136518053819, 1.3639364049316804, 0.23806361745695032]
"VOLKSWAGEN ATLAS 1ST GEN" = [1.4677006726964945, 1.6733266634075656, 0.12959584092073367]
"VOLKSWAGEN GOLF 7TH GEN" = [1.3750394140491293, 1.5814743077200641, 0.2018321939386586]
"VOLKSWAGEN JETTA 7TH GEN" = [1.2271623034089392, 1.216955117387, 0.19437384688370712]
"VOLKSWAGEN PASSAT 8TH GEN" = [1.3432120736752917, 1.7087275587362314, 0.19444383787326647]
"VOLKSWAGEN TIGUAN 2ND GEN" = [0.9711965500094828, 1.0001565939459098, 0.1465626137072916]
